[theme]
primaryColor = "#f42b55"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fff5f7"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
